name = "wispie"
version = "0.1.0"
description = "Render wisp HTTP responses into a human-readable representation"
licences = ["Apache-2.0"]
repository = { type = "github", user = "horvathandris", repo = "wispie" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
wisp = ">= 2.1.0 and < 3.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
contenty = ">= 1.1.0 and < 2.0.0"
glam = ">= 2.0.3 and < 3.0.0"
simplejson = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.4.1 and < 2.0.0"
